stages:
    - build
    - test

build:pip:
    stage: build
    image: python:2.7
    script:
        - pip install .

test:pytest:
    stage: test
    image: python:2.7
    script:
        - pytest --version
        - pytest