stages:
    - build
    - test

build:pip:
    stage: build
    image: python:2.7
    script:
        - echo "Building"
        - pip install .

test:pytest:
    stage: test
    image: python:2.7
    script:
        - echo "Running Tests"
        - pip install pytest --quiet
        - pytest