stages:
    - analysis
    - build
    - test

analysis:pylint:
    stage: analysis
    image: python:2.7
    script:
        - echo "Running static analysis with PyLint"
        - pip install pylint --quiet
        - pylint --ignored-classes=_socketobject *.py

build:pip:
    stage: build
    image: python:2.7
    script:
        - echo "Building"
        - pip install .

test:pytest:
    stage: test
    image: python:2.7
    script:
        - echo "Running Tests"
        - pip install pytest --quiet
        - pytest